services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    # network_mode: host
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "20m"
    healthcheck:
      test: mysqladmin ping -h localhost -pmegatransactdbrootuser
      interval: 10s
      retries: 15
      start_period: 5s
      timeout: 20s
    environment:
      - "TZ=UTC"
      - "MYSQL_ROOT_PASSWORD=megatransactdbrootuser"
      - "MYSQL_USER=megatransactdev"
      - "MYSQL_PASSWORD=megatransactapp"
      - "MYSQL_DATABASE=megatransactdb"
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
